# Install and Import Package

In [6]:
%pip install requests

Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (2025.10.5)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
import requests
import numpy as np
import pandas as pd

# --- Fix SSL certificate issue temporarily ---
import ssl
import nltk
import re
from collections import Counter
import nltk
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()
import time

[nltk_data] Error loading vader_lexicon: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>

# Part 2 Step 1: Crawl a Real-World Dataset

In [8]:
 #Extract Reddit Data Variable
subreddit = 'stocks'
limit = 300
timeframe = 'year' #hour, day, week, month, year, all
listing = 'top' # controversial, best, hot, new, random, rising, top
 
def get_reddit(subreddit, listing, limit, timeframe):
    try:
        base_url = f'https://www.reddit.com/r/{subreddit}/{listing}.json?limit={limit}&t={timeframe}'
        request = requests.get(base_url, headers = {'User-agent': 'SDPA'})
    except:
        print('An Error Occured')
    return request
 
r = get_reddit(subreddit,listing,limit,timeframe)

In [9]:
import json
data = json.loads(r.content)
data

{'kind': 'Listing',
 'data': {'after': 't3_1knyf2u',
  'dist': 100,
  'modhash': '',
  'geo_filter': '',
  'children': [{'kind': 't3',
    'data': {'approved_at_utc': None,
     'subreddit': 'stocks',
     'selftext': "Trump Asks Supreme Court to Let Him Fire Top Agency Officials\n\nSummary by Bloomberg Al\n\n■ President Donald Trump has asked the US Supreme Court to allow him to immediately fire top officials at two independent agencies.\n\n■ The case is testing a 90-year-old Supreme Court ruling that lets Congress shield high-ranking officials from being fired by the president.\n\nThe outcome could determine whether Trump has the power to fire Federal Reserve Chair Jerome Powell and could also impact the job security of other agency officials.\n\n[https://www.bloomberg.com/news/articles/2025-04-09/trump-asks-supreme-court-to-let-him-fire-top-agency-officials](https://www.bloomberg.com/news/articles/2025-04-09/trump-asks-supreme-court-to-let-him-fire-top-agency-officials)\n\n**If this happens, I'm seriously thinking about fully cashing out from the American market till mid/long-term, this guy is unstable af, not sure where to move really though...**",
     'author_fullname': 't2_4x9qg9sr',
     'saved': False,
     'mod_reason_title': None,
     'gilded': 0,
     'clicked': False,
     'title': 'PRESIDENT TRUMP JUST ASKED THE SUPREME COURT FOR THE AUTHORITY TO FIRE FEDERAL RESERVE CHAIR JEROME POWELL',
     'link_flair_richtext': [],
     'subreddit_name_prefixed': 'r/stocks',
     'hidden': False,
     'pwls': 6,
     'link_flair_css_class': '',
     'downs': 0,
     'top_awarded_type': None,
     'hide_score': False,
     'name': 't3_1jvzroz',
     'quarantine': False,
     'link_flair_text_color': 'dark',
     'upvote_ratio': 0.91,
     'author_flair_background_color': None,
     'subreddit_type': 'public',
     'ups': 52086,
     'total_awards_received': 0,
     'media_embed': {},
     'author_flair_template_id': None,
     'is_original_content': False,
     'user_reports': [],
     'secure_media': None,
     'is_reddit_media_domain': False,
     'is_meta': False,
     'category': None,
     'secure_media_embed': {},
     'link_flair_text': 'misleading title / false',
     'can_mod_post': False,
     'score': 52086,
     'approved_by': None,
     'is_created_from_ads_ui': False,
     'author_premium': False,
     'thumbnail': '',
     'edited': False,
     'author_flair_css_class': None,
     'author_flair_richtext': [],
     'gildings': {},
     'content_categories': None,
     'is_self': True,
     'mod_note': None,
     'created': 1744296575.0,
     'link_flair_type': 'text',
     'wls': 6,
     'removed_by_category': None,
     'banned_by': None,
     'author_flair_type': 'text',
     'domain': 'self.stocks',
     'allow_live_comments': False,
     'selftext_html': '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Trump Asks Supreme Court to Let Him Fire Top Agency Officials&lt;/p&gt;\n\n&lt;p&gt;Summary by Bloomberg Al&lt;/p&gt;\n\n&lt;p&gt;■ President Donald Trump has asked the US Supreme Court to allow him to immediately fire top officials at two independent agencies.&lt;/p&gt;\n\n&lt;p&gt;■ The case is testing a 90-year-old Supreme Court ruling that lets Congress shield high-ranking officials from being fired by the president.&lt;/p&gt;\n\n&lt;p&gt;The outcome could determine whether Trump has the power to fire Federal Reserve Chair Jerome Powell and could also impact the job security of other agency officials.&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.bloomberg.com/news/articles/2025-04-09/trump-asks-supreme-court-to-let-him-fire-top-agency-officials"&gt;https://www.bloomberg.com/news/articles/2025-04-09/trump-asks-supreme-court-to-let-him-fire-top-agency-officials&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;If this happens, I&amp;#39;m seriously thinking about fully cashing out from the American market till mid/long-term, this guy is unstable af, not sure where to move really though...&lt;/strong&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
     'likes': None,
     'suggested_sort': 'confidence',
     'banned_at_utc': None,
     'view_count': None,
     'archived': False,
     'no_follow': False,
     'is_crosspostable': False,
     'pinned': False,
     'over_18': False,
     'all_awardings': [],
     'awarders': [],
     'media_only': False,
     'link_flair_template_id': '3f699d26-8b74-11ec-8077-9a82b5738a34',
     'can_gild': False,
     'spoiler': False,
     'locked': False,
     'author_flair_text': None,
     'treatment_tags': [],
     'visited': False,
     'removed_by': None,
     'num_reports': None,
     'distinguished': None,
     'subreddit_id': 't5_2qjfk',
     'author_is_blocked': False,
     'mod_reason_by': None,
     'removal_reason': None,
     'link_flair_background_color': '#ffb000',
     'id': '1jvzroz',
     'is_robot_indexable': True,
     'report_reasons': None,
     'author': 'Tiny-Injury',
     'discussion_type': None,
     'num_comments': 3617,
     'send_replies': False,
     'contest_mode': False,
     'mod_reports': [],
     'author_patreon_flair': False,
     'author_flair_text_color': None,
     'permalink': '/r/stocks/comments/1jvzroz/president_trump_just_asked_the_supreme_court_for/',
     'stickied': False,
     'url': 'https://www.reddit.com/r/stocks/comments/1jvzroz/president_trump_just_asked_the_supreme_court_for/',
     'subreddit_subscribers': 9016720,
     'created_utc': 1744296575.0,
     'num_crossposts': 27,
     'media': None,
     'is_video': False}},
   {'kind': 't3',
    'data': {'approved_at_utc': None,
     'subreddit': 'stocks',
     'selftext': 'The U.S. Suicide Hotline:\n\nDial 988, text 988, or visit 988lifeline.org for online chat. 988 is a free, confidential service available 24/7 for anyone experiencing emotional distress, a mental health crisis, or thoughts of suicide. You can call, text, or chat with trained counselors who provide support and resources',
     'author_fullname': 't2_c8akorh9c',
     'saved': False,
     'mod_reason_title': None,
     'gilded': 0,
     'clicked': False,
     'title': 'Suicide hotline',
     'link_flair_richtext': [],
     'subreddit_name_prefixed': 'r/stocks',
     'hidden': False,
     'pwls': 6,
     'link_flair_css_class': 'advice',
     'downs': 0,
     'top_awarded_type': None,
     'hide_score': False,
     'name': 't3_1jrmmdq',
     'quarantine': False,
     'link_flair_text_color': 'light',
     'upvote_ratio': 0.91,
     'author_flair_background_color': None,
     'subreddit_type': 'public',
     'ups': 49725,
     'total_awards_received': 0,
     'media_embed': {},
     'author_flair_template_id': None,
     'is_original_content': False,
     'user_reports': [],
     'secure_media': None,
     'is_reddit_media_domain': False,
     'is_meta': False,
     'category': None,
     'secure_media_embed': {},
     'link_flair_text': 'Advice',
     'can_mod_post': False,
     'score': 49725,
     'approved_by': None,
     'is_created_from_ads_ui': False,
     'author_premium': False,
     'thumbnail': '',
     'edited': False,
     'author_flair_css_class': None,
     'author_flair_richtext': [],
     'gildings': {},
     'content_categories': None,
     'is_self': True,
     'mod_note': None,
     'created': 1743800556.0,
     'link_flair_type': 'text',
     'wls': 6,
     'removed_by_category': None,
     'banned_by': None,
     'author_flair_type': 'text',
     'domain': 'self.stocks',
     'allow_live_comments': False,
     'selftext_html': '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;The U.S. Suicide Hotline:&lt;/p&gt;\n\n&lt;p&gt;Dial 988, text 988, or visit 988lifeline.org for online chat. 988 is a free, confidential service available 24/7 for anyone experiencing emotional distress, a mental health crisis, or thoughts of suicide. You can call, text, or chat with trained counselors who provide support and resources&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
     'likes': None,
     'suggested_sort': 'confidence',
     'banned_at_utc': None,
     'view_count': None,
     'archived': False,
     'no_follow': False,
     'is_crosspostable': False,
     'pinned': False,
     'over_18': False,
     'all_awardings': [],
     'awarders': [],
     'media_only': False,
     'link_flair_template_id': '823be0a6-65e6-11e5-9784-125ee764bc01',
     'can_gild': False,
     'spoiler': False,
     'locked': False,
     'author_flair_text': None,
     'treatment_tags': [],
     'visited': False,
     'removed_by': None,
     'num_reports': None,
     'distinguished': None,
     'subreddit_id': 't5_2qjfk',
     'author_is_blocked': False,
     'mod_reason_by': None,
     'removal_reason': None,
     'link_flair_background_color': '#646d73',
     'id': '1jrmmdq',
     'is_robot_indexable': True,
     'report_reasons': None,
     'author': 'rmoodsrajoke',
     'discussion_type': None,
     'num_comments': 1420,
     'send_replies': True,
     'contest_mode': False,
     'mod_reports': [],
     'author_patreon_flair': False,
     'author_flair_text_color': None,
     'permalink': '/r/stocks/comments/1jrmmdq/suicide_hotline/',
     'stickied': False,
     'url': 'https://www.reddit.com/r/stocks/comments/1jrmmdq/suicide_hotline/',
     'subreddit_subscribers': 9016720,
     'created_utc': 1743800556.0,
     'num_crossposts': 14,
     'media': None,
     'is_video': False}},
   {'kind': 't3',
    'data': {'approved_at_utc': None,
     'subreddit': 'stocks',
     'selftext': 'As reported by Axios, Trump was shaken Monday after meeting with CEO’s of top retail companies like Target. They warned him that disrupted supply chains due to his China tariffs would mean empty shelves and soaring prices very soon. You can imagine how the optics of bare shelves all around the country would look. \n\nMaybe they will get exemptions as Trump’s crony capitalism marches on but a huge number of small businesses won’t and will go under.\n\nSomewhere Xi is smirking. \n\nhttps://dailyboulder.com/shaken-trump-makes-u-turn-on-tariffs-after-being-rattled-by-dire-ceo-warning/',
     'author_fullname': 't2_4xkmqu58',
     'saved': False,
     'mod_reason_title': None,
     'gilded': 0,
     'clicked': False,
     'title': 'Now we know. It was Retail CEOS who got to Trump on Monday',
     'link_flair_richtext': [],
     'subreddit_name_prefixed': 'r/stocks',
     'hidden': False,
     'pwls': 6,
     'link_flair_css_class': '',
     'downs': 0,
     'top_awarded_type': None,
     'hide_score': False,
     'name': 't3_1k6pihz',
     'quarantine': False,
     'link_flair_text_color': 'light',
     'upvote_ratio': 0.92,
     'author_flair_background_color': None,
     'subreddit_type': 'public',
     'ups': 47594,
     'total_awards_received': 0,
     'media_embed': {},
     'author_flair_template_id': None,
     'is_original_content': False,
     'user_reports': [],
     'secure_media': None,
     'is_reddit_media_domain': False,
     'is_meta': False,
     'category': None,
     'secure_media_embed': {},
     'link_flair_text': 'Broad market news',
     'can_mod_post': False,
     'score': 47594,
     'approved_by': None,
     'is_created_from_ads_ui': False,
     'author_premium': False,
     'thumbnail': '',
     'edited': False,
     'author_flair_css_class': None,
     'author_flair_richtext': [],
     'gildings': {},
     'content_categories': None,
     'is_self': True,
     'mod_note': None,
     'created': 1745492967.0,
     'link_flair_type': 'text',
     'wls': 6,
     'removed_by_category': None,
     'banned_by': None,
     'author_flair_type': 'text',
     'domain': 'self.stocks',
     'allow_live_comments': False,
     'selftext_html': '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;As reported by Axios, Trump was shaken Monday after meeting with CEO’s of top retail companies like Target. They warned him that disrupted supply chains due to his China tariffs would mean empty shelves and soaring prices very soon. You can imagine how the optics of bare shelves all around the country would look. &lt;/p&gt;\n\n&lt;p&gt;Maybe they will get exemptions as Trump’s crony capitalism marches on but a huge number of small businesses won’t and will go under.&lt;/p&gt;\n\n&lt;p&gt;Somewhere Xi is smirking. &lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://dailyboulder.com/shaken-trump-makes-u-turn-on-tariffs-after-being-rattled-by-dire-ceo-warning/"&gt;https://dailyboulder.com/shaken-trump-makes-u-turn-on-tariffs-after-being-rattled-by-dire-ceo-warning/&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
     'likes': None,
     'suggested_sort': 'confidence',
     'banned_at_utc': None,
     'view_count': None,
     'archived': False,
     'no_follow': False,
     'is_crosspostable': False,
     'pinned': False,
     'over_18': False,
     'all_awardings': [],
     'awarders': [],
     'media_only': False,
     'link_flair_template_id': '283289f4-14eb-11ee-8c5b-06269d4c3b1f',
     'can_gild': False,
     'spoiler': False,
     'locked': False,
     'author_flair_text': None,
     'treatment_tags': [],
     'visited': False,
     'removed_by': None,
     'num_reports': None,
     'distinguished': None,
     'subreddit_id': 't5_2qjfk',
     'author_is_blocked': False,
     'mod_reason_by': None,
     'removal_reason': None,
     'link_flair_background_color': '#349e48',
     'id': '1k6pihz',
     'is_robot_indexable': True,
     'report_reasons': None,
     'author': 'Epicurus-fan',
     'discussion_type': None,
     'num_comments': 2885,
     'send_replies': True,
     'contest_mode': False,
     'mod_reports': [],
     'author_patreon_flair': False,
     'author_flair_text_color': None,
     'permalink': '/r/stocks/comments/1k6pihz/now_we_know_it_was_retail_ceos_who_got_to_trump/',
     'stickied': False,
     'url': 'https://www.reddit.com/r/stocks/comments/1k6pihz/now_we_know_it_was_retail_ceos_who_got_to_trump/',
     'subreddit_subscribers': 9016720,
     'created_utc': 1745492967.0,
     'num_crossposts': 22,
     'media': None,
     'is_video': False}},
   {'kind': 't3',
    'data': {'approved_at_utc': None,
     'subreddit': 'stocks',
     'selftext': "[https://www.reuters.com/world/china-japan-south-korea-will-jointly-respond-us-tariffs-chinese-state-media-says-2025-03-31/](https://www.reuters.com/world/china-japan-south-korea-will-jointly-respond-us-tariffs-chinese-state-media-says-2025-03-31/)\n\nBEIJING, March 31 (Reuters) - China, Japan and South Korea agreed to jointly respond to U.S. tariffs, a social media account affiliated with Chinese state broadcaster CCTV said on Monday.The comments came after the three countries held their first [economic dialogue](https://www.reuters.com/world/asia-pacific/south-korea-china-japan-agree-promote-regional-trade-trump-tariffs-loom-2025-03-30/) in five years on Sunday, seeking to facilitate regional trade as the Asian export powers brace against U.S. President Donald Trump's tariffs.\n\nEU hasn't even clap back yet.\n\nEdit. For those who say this is Chinese media, the other countries are not refuting this claim. China is taking the lead on this. For EU, I think Germany will take the lead on that.\n\nEdit 2. Since there are many comments regarding this being Chinese propaganda, below are more links to prove that this isn't just coming from Chinese Media. \n\n[https://www.bloomberg.com/news/articles/2025-03-30/china-japan-s-korea-renew-free-trade-call-vow-to-build-ties](https://www.bloomberg.com/news/articles/2025-03-30/china-japan-s-korea-renew-free-trade-call-vow-to-build-ties)\n\n[https://www.newsweek.com/trump-tariffs-pushing-asian-allies-toward-china-2052937](https://www.newsweek.com/trump-tariffs-pushing-asian-allies-toward-china-2052937)\n\n[https://www.france24.com/en/live-news/20250330-china-south-korea-and-japan-agree-to-strengthen-free-trade](https://www.france24.com/en/live-news/20250330-china-south-korea-and-japan-agree-to-strengthen-free-trade)\n\n[https://www.japantimes.co.jp/business/2025/03/30/japan-china-south-korea-trade-ministers/](https://www.japantimes.co.jp/business/2025/03/30/japan-china-south-korea-trade-ministers/)\n\n[https://www.globaltimes.cn/page/202503/1331179.shtml](https://www.globaltimes.cn/page/202503/1331179.shtml)\n\n[https://asia.nikkei.com/Economy/Trade-war/Trump-s-threat-to-free-trade-brings-China-Japan-South-Korea-closer](https://asia.nikkei.com/Economy/Trade-war/Trump-s-threat-to-free-trade-brings-China-Japan-South-Korea-closer)",
     'author_fullname': 't2_8nz8u8x2',
     'saved': False,
     'mod_reason_title': None,
     'gilded': 0,
     'clicked': False,
     'title': 'America is going to get rocked. China, Japan, South Korea will jointly respond to US tariffs, Chinese state media says',
     'link_flair_richtext': [],
     'subreddit_name_prefixed': 'r/stocks',
     'hidden': False,
     'pwls': 6,
     'link_flair_css_class': '',
     'downs': 0,
     'top_awarded_type': None,
     'hide_score': False,
     'name': 't3_1jo76s8',
     'quarantine': False,
     'link_flair_text_color': 'light',
     'upvote_ratio': 0.9,
     'author_flair_background_color': None,
     'subreddit_type': 'public',
     'ups': 46915,
     'total_awards_received': 0,
     'media_embed': {},
     'author_flair_template_id': None,
     'is_original_content': False,
     'user_reports': [],
     'secure_media': None,
     'is_reddit_media_domain': False,
     'is_meta': False,
     'category': None,
     'secure_media_embed': {},
     'link_flair_text': 'Broad market news',
     'can_mod_post': False,
     'score': 46915,
     'approved_by': None,
     'is_created_from_ads_ui': False,
     'author_premium': False,
     'thumbnail': '',
     'edited': 1743447713.0,
     'author_flair_css_class': None,
     'author_flair_richtext': [],
     'gildings': {},
     'content_categories': None,
     'is_self': True,
     'mod_note': None,
     'created': 1743438131.0,
     'link_flair_type': 'text',
     'wls': 6,
     'removed_by_category': None,
     'banned_by': None,
     'author_flair_type': 'text',
     'domain': 'self.stocks',
     'allow_live_comments': False,

In [10]:
temp = []
for i in range(100):
    post = data['data']['children'][i]['data']
    temp.append([post['title'], post['ups'], post['link_flair_text'], post['num_comments'], post['top_awarded_type'], post['selftext'], post['created_utc'], post['id']])
    
title = np.array(temp)
first_hundred = pd.DataFrame(title, columns=['Title', 'Upvotes', 'Flair', 'Num_Comments', 'Awards','Body', 'Created_UTC', 'Post_ID'])
print(first_hundred)

                                                Title Upvotes  \
0   PRESIDENT TRUMP JUST ASKED THE SUPREME COURT F...   52086
1                                     Suicide hotline   49725
2   Now we know. It was Retail CEOS who got to Tru...   47594
3   America is going to get rocked. China, Japan, ...   46915
4   China Officially Makes Statement Stating That ...   46880
..                                                ...     ...
95                  China is playing the US right now    5132
96  Billionaire Ray Dalio: ‘I’m worried about some...    5121
97  Is it possible that Trump’s tariffs are a mass...    5096
98   Trump Taps Palantir to Compile Data on Americans    5064
99  Donald Trump says US will set new tariff rates...    5055

                       Flair Num_Comments Awards  \
0   misleading title / false         3617   None
1                     Advice         1420   None
2          Broad market news         2885   None
3          Broad market news         3595   None
4          Broad market news         3167   None
..                       ...          ...    ...
95                      None          782   None
96                      None          423   None
97        Rule 3: Low Effort          689   None
98              Company News          430   None
99         Broad market news          843   None

                                                 Body   Created_UTC  Post_ID
0   Trump Asks Supreme Court to Let Him Fire Top A...  1744296575.0  1jvzroz
1   The U.S. Suicide Hotline:\n\nDial 988, text 98...  1743800556.0  1jrmmdq
2   As reported by Axios, Trump was shaken Monday ...  1745492967.0  1k6pihz
3   [https://www.reuters.com/world/china-japan-sou...  1743438131.0  1jo76s8
4   China vows to stand firm, urges nations to res...  1745894404.0  1kadl0p
..                                                ...           ...      ...
95  USD weakening. Yuan weakening. Treasury yields...  1744167676.0  1juvwsy
96  Key Points\n\n* Bridgewater founder Ray Dalio ...  1744567553.0  1jydvrf
97  EDIT: I’m not an investor, just asking a quest...  1743767133.0  1jr9uxv
98  "In March, President Trump signed an executive...  1748620846.0  1kz7xkg
99  [From the FT](https://www.ft.com/content/1f5f7...  1747394718.0  1knyf2u

[100 rows x 8 columns]

In [11]:
#Token for after parameter
after_token = data['data']['children'][99]['kind']+ '_' + data['data']['children'][99]['data']['id']
#After Function to get next 100 posts
def get_reddit_after(subreddit, listing, limit, timeframe, after_token):
    '''This function gets Reddit posts after a specific token'''
    try:
        base_url = f'https://www.reddit.com/r/{subreddit}/{listing}.json?limit={limit}&t={timeframe}&after={after_token}'
        request = requests.get(base_url, headers = {'User-agent': 'SDPA'})
    except:
        print('An Error Occured')
        return None
    return request
r_new = get_reddit_after(subreddit,listing,limit,timeframe, after_token)
new_data = json.loads(r_new.content)
new_data

temp = []
for i in range(100):
    post = new_data['data']['children'][i]['data']
    temp.append([post['title'], post['ups'], post['link_flair_text'], post['num_comments'], post['top_awarded_type'], post['selftext'],post['created_utc'], post['id']]), 
    
title = np.array(temp)
second_hundred = pd.DataFrame(title, columns=['Title', 'Upvotes', 'Flair', 'Num_Comments', 'Awards', 'Body', 'Created_UTC', 'Post_ID'])
print(second_hundred)

                                                Title Upvotes  \
0   This is a disaster of epic proportion”  Trump ...    4929
1   Elon Musk defends $1 trillion pay package: ‘I ...    4836
2   The era of American stock market exceptionalis...    4826
3   Bloomberg: Markets are Discovering that the Re...    4727
4       Tesla just got even more bad news from Europe    4684
..                                                ...     ...
95               Apple Announces $100B Share Buyback.    2891
96    The Wall Street Journal explains Trump tariffs.    2871
97  The Mar-A-Lago Accord - they are crashing the ...    2867
98  Trump delays tariffs! For automakers. The rest...    2838
99    Don’t Look at Stock Markets. Look at the Ports.    2829

                            Flair Num_Comments Awards  \
0              Company Discussion          710   None
1                    Company News          600   None
2                            None          587   None
3               Broad market news          295   None
4                    Company News          540   None
..                            ...          ...    ...
95                           None          447   None
96                           None          457   None
97  Off topic: Political Bullshit          146   None
98                           None          339   None
99              Broad market news          466   None

                                                 Body   Created_UTC  Post_ID
0   Anyone else watching this Trump vs Musk drama ...  1749251929.0  1l56hgo
1                                                      1761336796.0  1of85md
2   https://www.telegraph.co.uk/money/investing/am...  1745076348.0  1k2ys45
3   Two months into Donald Trump’s second term, th...  1745330928.0  1k5789e
4   "Tesla's sales in Europe plunged in the first ...  1742919169.0  1jjn4aa
..                                                ...           ...      ...
95  Apple’s CEO. “We were happy to welcome iPhone ...  1746132886.0  1kcjdo4
96  I had a similar analyses, but this coming from...  1745167872.0  1k3qwu1
97  So I've posted around this paper by Stephen Mi...  1742045423.0  1jbv5dh
98  [https://www.cnbc.com/2025/03/05/trump-grants-...  1741202648.0  1j4bg0p
99  The Atlantic: https://www.theatlantic.com/econ...  1746321624.0  1ke88st

[100 rows x 8 columns]

In [12]:
df = pd.concat([first_hundred, second_hundred], ignore_index=True)
df.to_csv('reddit_python_top_300_posts_2023.csv', index=False)
df

,Title,Upvotes,Flair,Num_Comments,Awards,Body,Created_UTC,Post_ID
0,PRESIDENT TRUMP JUST ASKED THE SUPREME COURT F...,52086,misleading title / false,3617,None,Trump Asks Supreme Court to Let Him Fire Top A...,1744296575.0,1jvzroz
1,Suicide hotline,49725,Advice,1420,None,"The U.S. Suicide Hotline:\n\nDial 988, text 98...",1743800556.0,1jrmmdq
2,Now we know. It was Retail CEOS who got to Tru...,47594,Broad market news,2885,None,"As reported by Axios, Trump was shaken Monday ...",1745492967.0,1k6pihz
3,"America is going to get rocked. China, Japan, ...",46915,Broad market news,3595,None,[https://www.reuters.com/world/china-japan-sou...,1743438131.0,1jo76s8
4,China Officially Makes Statement Stating That ...,46880,Broad market news,3167,None,"China vows to stand firm, urges nations to res...",1745894404.0,1kadl0p
...,...,...,...,...,...,...,...,...
195,Apple Announces $100B Share Buyback.,2891,None,447,None,Apple’s CEO. “We were happy to welcome iPhone ...,1746132886.0,1kcjdo4
196,The Wall Street Journal explains Trump tariffs.,2871,None,457,None,"I had a similar analyses, but this coming from...",1745167872.0,1k3qwu1
197,The Mar-A-Lago Accord - they are crashing the ...,2867,Off topic: Political Bullshit,146,None,So I've posted around this paper by Stephen Mi...,1742045423.0,1jbv5dh
198,Trump delays tariffs! For automakers. The rest...,2838,None,339,None,[https://www.cnbc.com/2025/03/05/trump-grants-...,1741202648.0,1j4bg0p
199,Don’t Look at Stock Markets. Look at the Ports.,2829,Broad market news,466,None,The Atlantic: https://www.theatlantic.com/econ...,1746321624.0,1ke88st

# Frequent word in subreddit

In [13]:
# --- Fix SSL certificate issue temporarily ---
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

# --- Now download stopwords safely ---
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>

False

In [14]:
# ----- Download stopwords once -----
# (Run this only the first time; NLTK will remember afterward)
nltk.download('stopwords')

# ----- Define stopwords -----
stop_words = set(stopwords.words('english'))

# You can add your own extra words if you like
custom_stopwords = {'python', 'https', 'reddit', 'www', 'com'}
stop_words.update(custom_stopwords)

# ----- Prepare and clean titles -----
# Convert all titles to lowercase
title_clean = df['Title'].astype(str).str.lower()

# Combine all titles into one long text string
all_titles = ' '.join(title_clean)

# Extract only words (remove punctuation/numbers)
words = re.findall(r'\b[a-zA-Z]{3,}\b', all_titles)

# Filter out stopwords
filtered_words = [w for w in words if w not in stop_words]

# ----- Count the most frequent words -----
word_counts = Counter(filtered_words)

# Get top 30 most common words
top_words = word_counts.most_common(30)

# ----- Display results -----
print("\nTop 30 most frequent words in Reddit post titles:")
for word, count in top_words:
    print(f"{word:15} {count}")

Top 30 most frequent words in Reddit post titles:
trump           83
tariffs         47
says            27
china           26
tesla           25
market          23
tariff          16
musk            16
billion         12
stock           12
elon            10
powell          9
chinese         9
trade           9
canada          8
tsla            7
buy             6
breaking        6
since           6
back            6
walmart         6
prices          6
goods           6
american        5
white           5
house           5
amazon          5
economy         5
year            5
jobs            5

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>

In [15]:
# ----- Import libraries -----
import re
from collections import Counter
import nltk
from nltk.corpus import stopwords

# ----- Download stopwords once -----
# (Run this only the first time; NLTK will remember afterward)
nltk.download('stopwords')

# ----- Define stopwords -----
stop_words = set(stopwords.words('english'))

# You can add your own extra words if you like
custom_stopwords = {'python', 'https', 'reddit', 'www', 'com'}
stop_words.update(custom_stopwords)

# ----- Prepare and clean titles -----
# Convert all titles to lowercase
title_clean = df['Title'].astype(str).str.lower()

# Combine all titles into one long text string
all_titles = ' '.join(title_clean)

# Extract only words (remove punctuation/numbers)
words = re.findall(r'\b[a-zA-Z]{3,}\b', all_titles)

# Filter out stopwords
filtered_words = [w for w in words if w not in stop_words]

# ----- Count the most frequent words -----
word_counts = Counter(filtered_words)

# Get top 30 most common words
top_words = word_counts.most_common(30)

# ----- Display results -----
print("\nTop 30 most frequent words in Reddit post titles:")
for word, count in top_words:
    print(f"{word:15} {count}")

Top 30 most frequent words in Reddit post titles:
trump           83
tariffs         47
says            27
china           26
tesla           25
market          23
tariff          16
musk            16
billion         12
stock           12
elon            10
powell          9
chinese         9
trade           9
canada          8
tsla            7
buy             6
breaking        6
since           6
back            6
walmart         6
prices          6
goods           6
american        5
white           5
house           5
amazon          5
economy         5
year            5
jobs            5

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>

# Sentiment Analyze Comment

In [20]:
results = []
for body in df['Body']:
    sentiment = sia.polarity_scores(body)
    sentiment['body'] = body
    compound = sentiment['compound']
    if compound >= 0.05:
        sentiment['Sentiment_Label'] = 'Positive'
    elif compound <= -0.05:
        sentiment['Sentiment_Label'] = 'Negative'
    else:
        sentiment['Sentiment_Label'] = 'Neutral'

    results.append(sentiment)
        
df_results = pd.DataFrame(results)
df_results

,neg,neu,pos,compound,body,Sentiment_Label
0,0.127,0.733,0.140,0.4094,Trump Asks Supreme Court to Let Him Fire Top A...,Positive
1,0.257,0.624,0.119,-0.8979,"The U.S. Suicide Hotline:\n\nDial 988, text 98...",Negative
2,0.048,0.864,0.088,0.5346,"As reported by Axios, Trump was shaken Monday ...",Positive
3,0.015,0.970,0.015,0.0258,[https://www.reuters.com/world/china-japan-sou...,Neutral
4,0.099,0.814,0.086,-0.5181,"China vows to stand firm, urges nations to res...",Negative
...,...,...,...,...,...,...
195,0.020,0.758,0.222,0.9601,Apple’s CEO. “We were happy to welcome iPhone ...,Positive
196,0.100,0.780,0.120,0.8770,"I had a similar analyses, but this coming from...",Positive
197,0.083,0.841,0.076,-0.6231,So I've posted around this paper by Stephen Mi...,Negative
198,0.182,0.723,0.095,-0.6763,[https://www.cnbc.com/2025/03/05/trump-grants-...,Negative
199,0.143,0.793,0.065,-0.9989,The Atlantic: https://www.theatlantic.com/econ...,Negative

In [17]:
results = []
for headline in df['Title']:
    sentiment = sia.polarity_scores(headline)
    sentiment['headline'] = headline
    results.append(sentiment)
df_results = pd.DataFrame(results)
df_results

,neg,neu,pos,compound,headline
0,0.113,0.657,0.230,0.3612,PRESIDENT TRUMP JUST ASKED THE SUPREME COURT F...
1,0.818,0.182,0.000,-0.6705,Suicide hotline
2,0.000,1.000,0.000,0.0000,Now we know. It was Retail CEOS who got to Tru...
3,0.000,1.000,0.000,0.0000,"America is going to get rocked. China, Japan, ..."
4,0.000,0.772,0.228,0.6808,China Officially Makes Statement Stating That ...
...,...,...,...,...,...
195,0.000,0.645,0.355,0.2960,Apple Announces $100B Share Buyback.
196,0.000,1.000,0.000,0.0000,The Wall Street Journal explains Trump tariffs.
197,0.000,1.000,0.000,0.0000,The Mar-A-Lago Accord - they are crashing the ...
198,0.000,1.000,0.000,0.0000,Trump delays tariffs! For automakers. The rest...
199,0.000,1.000,0.000,0.0000,Don’t Look at Stock Markets. Look at the Ports.